name: Qt CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y qt5-default
    
    - name: Configure
      run: qmake
    
    - name: Build
      run: make
    
    - name: Run tests
      run: make check
    
    - name: Package
      run: make distcheck
